import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Link from 'next/link'


export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState(false)

  useEffect(() => {
    if (localStorage.getItem("e_key") && localStorage.getItem("a_key") && localStorage.getItem("user")) {
      setIsLoggedIn(true)
    } else {
      setIsLoggedIn(false)
    }
  }, [])

  return (
    <div className="">
      <Head>
        <title>0xNotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex p-4 w-screen text-white bg-gray-700">
        <div className="my-auto">
          <img src></img>
          <span>0xNotes</span>
        </div>
        <div style={{display: isLoggedIn ? 'none' : 'block'}} className="ml-auto">
          <Link href="/login">
            <a className="mx-1">Login</a>
          </Link>
          <Link href="/signup">
            <button className="accent my-auto mx-1 px-2 py-1 rounded-md">Sign Up</button>
          </Link>
        </div>
        <div style={{display: isLoggedIn ? 'block' : 'none'}} className="ml-auto">
          <Link href="/dash">
            <button className="accent my-auto mx-1 px-2 py-1 rounded-md">Dashboard</button>
          </Link>
        </div>
      </header>

      <main className="">
        <a className="text-white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a>

      </main>

      <footer className="p-4 w-screen text-white bg-gray-700">&copy; Copyright 2021 0xNotes &#183; GitHub &#183; Terms &#183; Privacy</footer>
    </div>
  )
}
